version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
      # Ajout de la ligne pour le cache de pip
      - pip_cache:/root/.cache/pip
    depends_on:
      - db
    networks:
      - expert_comptable_net

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expert_comptable_net

networks:
  expert_comptable_net:
    driver: bridge

volumes:
  mysql_data:
  # Déclaration du nouveau volume pour le cache
  pip_cache: